version: 0.0.{build}
skip_branch_with_pr: true
image: Visual Studio 2017
services:
- iis
- mssql2017
install:
- ps: >-
     Install-Module ParTech.SimpleInstallScripts -RequiredVersion "0.0.80" -Force -SkipPublisherCheck -AllowClobber
before_build:
- ps: >-
     Start-FileDownload 'https://ci.appveyor.com/api/projects/steviemcg/helixbase/artifacts/artifacts%2fHelixbase.Website.zip' wdp.zip
build_script :
- ps: >-
    Install-Sitecore91 -Prefix "helixbase" `
            -Parameters @{SitecoreSiteName="demo.helixbase"} `
            -DownloadBase $Env:DownloadBase `
            -SitecoreVersion "910XP0" `
            -DoInstallPrerequisites `
            -DoRebuildLinkDatabases:$false `
            -DoRebuildSearchIndexes:$false `
            -DoDeployMarketingDefinitions:$false `
            -SQLServer . `
            -SqlAdminUser sa `
            -SqlAdminPassword 'Password12!'
after_build:
- ps: >-
    Start-FileDownload 'https://ci.appveyor.com/api/projects/steviemcg/helixbase/artifacts/artifacts%2fHelixbase.Website.zip' wdp.zip

    & "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" `
            -verb:sync -source:package=wdp.zip `
            -dest:auto,includeAcls=`"False`" `
            -enableRule:DoNotDeleteRule `
            -disableLink:AppPoolExtension `
            -disableLink:ContentExtension `
            -disableLink:CertificateExtension `
            -setParam:name=`"IIS Web Application Name`",value=`"demo.helixbase`"

    Import-Module .\build\functions.psm1

    $UnicornSecret = -join ((48..57) + (97..122) | Get-Random -Count 64 | ForEach-Object {[char]$_})
    
    $SrcDir = Resolve-Path ".\src"
    
    Set-SourceFolder ".\build\SourceFolder.config" "c:\inetpub\wwwroot\demo.helixbase" $SrcDir
    
    Set-Unicorn-Shared-Secret ".\build\Unicorn.SharedSecret.config" "c:\inetpub\wwwroot\demo.helixbase" $UnicornSecret
    
    Set-PublishUrl "$SrcDir\Website\code\Properties\PublishProfiles\Local.pubxml" "c:\inetpub\wwwroot\demo.helixbase"
    
    Sync-Unicorn -ControlPanelUrl "http://demo.helixbase/unicorn.aspx" -SharedSecret $UnicornSecret
test_script:
- ps: 'Test-Site "http://demo.helixbase"'
on_success:
- ps: '$blockRdp = $true; iex ((new-object net.webclient).DownloadString(''https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1''))'
on_failure:
- ps: '$blockRdp = $true; iex ((new-object net.webclient).DownloadString(''https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1''))'